version: "3"

services:

  web:
    image: "python2-django"
    build: .
    volumes:
      - ./src:/src
    environment: 
      # This is used to avoid creation of pyc files at development time
      PYTHONDONTWRITEBYTECODE: 1
      #PYTHON_OPTS:
      WAIT_HOSTS: db:5432
    ports:
      - "8000:8000"

  db:
    image: "postgres:9-alpine"
    #hostname: postgres
    ports:
      - "5432:5432"
